default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MySQL_PASSWORD"] %>
  host: db

development:
  <<: *default
  database: SampleAppKauru_development

test:
  <<: *default
  database: SampleAppKauru_test

production:
  <<: *default
  database: SampleAppKauru_production
  username: SampleAppKauru
  password: <%= ENV['SAMPLEAPPKAURU_DATABASE_PASSWORD'] %>
